<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'hd321kbps\\blog\\Plugin' => 'plugins\\hd321kbps\\blog\\Plugin.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'hd321kbps\\blog\\Controllers\\posts' => 'plugins\\hd321kbps\\blog\\controllers\\posts.php',
  'hd321kbps\\blog\\Controllers\\categories' => 'plugins\\hd321kbps\\blog\\controllers\\categories.php',
  'system\\Controllers\\eventlogs' => 'modules\\system\\controllers\\eventlogs.php',
  'hd321kbps\\blog\\Controllers\\post' => 'plugins\\hd321kbps\\blog\\controllers\\post.php',
  'Hd321kbps\\Blog\\Models\\Post' => 'plugins\\hd321kbps\\blog\\models\\Post.php',
  'hd321kbps\\blog\\Controllers\\category' => 'plugins\\hd321kbps\\blog\\controllers\\category.php',
  'Hd321kbps\\Blog\\Models\\Category' => 'plugins\\hd321kbps\\blog\\models\\Category.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
  'October\\Demo\\Components\\Todo' => 'plugins\\october\\demo\\components\\Todo.php',
  'Hd321kbps\\Blog\\Components\\Post' => 'plugins\\hd321kbps\\blog\\components\\Post.php',
  'Hd321kbps\\Blog\\Components\\Posts' => 'plugins\\hd321kbps\\blog\\components\\Posts.php',
  'hd321kbps\\Blog\\Models\\Post' => 'plugins\\hd321kbps\\blog\\models\\Post.php',
);